runtime: nodejs14
service: testnet-resolver
env_variables:
  PURESTAKE_CLIENT_URL: "https://mainnet-algorand.api.purestake.io/ps2"
  PURESTAKE_INDEXER_URL: "https://mainnet-algorand.api.purestake.io/idx2"
  PURESTAKE_TESTNET_CLIENT_URL: "https://testnet-algorand.api.purestake.io/ps"
  PURESTAKE_TESTNET_INDEXER_URL: "https://testnet-algorand.api.purestake.io/idx2"
  PURESTAKE_API_KEY: "iG4m46pAcU5ws8WYhgYPu1rywUbfYT2DaAfSs9Tv"
  APP_ID: "628095415"
  CHAR_3_AMOUNT: "150000000"
  CHAR_4_AMOUNT: "50000000"
  CHAR_5_AMOUNT: "5000000"
  TRANSFER_FEE: "2000000"
  TESTNET_APP_ID: "75101786"
  TESTNET_ESCROW: "ACFFHRILZQ6W2UDNYYTHV55YS6MZWJR4PEDVBFAL575FFK4AT4UBCO3SXE"
  MAINNET_ESCROW: "SYGCDTWGBXKV4ZL5YAWSYAVOUC25U2XDB6SMQHLRCTYVF566TQZ3EOABH4"
  NETWORK: "TestNet"
  
instance_class: F2
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic